# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Unpaid Opportunities
description: > # this means to ignore newlines until "baseurl:"
  Are you highly qualified and willing to work for free?
baseurl: "/unpaid-opportunity" # the subpath of your site, e.g. /blog
url: "http://erickpeirson.github.io" # the base hostname & protocol for your site
github_username:  kroppheather
github_username_2:  erickpeirson


# Build settings
markdown: kramdown
